name: salute
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  font_awesome_flutter: ^10.2.1

  flutter:
    sdk: flutter
  localization: ^2.1.0
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  animate_icons: ^2.0.0
  date_picker_timeline: ^1.2.3
  provider: ^6.0.5
  fluttertoast: ^8.1.2
  http: ^0.13.5
  location: ^4.4.0
  shared_preferences: ^2.0.17
  flutter_advanced_networkimage_2: ^2.0.1
  flutter_localization: ^0.1.10
  flutter_localizations:
    sdk: flutter

  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: SelebgramDemo
      fonts:
        - asset: assets/fonts/SelebgramDemoRegular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
