name: salute
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  font_awesome_flutter: ^10.2.1

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  animate_icons: ^2.0.0
  date_picker_timeline: ^1.2.3
  provider: ^6.0.5
  fluttertoast: ^8.1.2
  http: ^0.13.5
  shared_preferences: ^2.0.17
  flutter_advanced_networkimage_2: ^2.0.1
  toast: ^0.3.0
  url_launcher: ^6.1.5
  flutter_localizations:
    sdk: flutter

  

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
flutter_icons:
  android: false
  ios: true
  image_path: "assets/images/app_logo.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: SelebgramDemo
      fonts:
        - asset: assets/fonts/SelebgramDemoRegular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
